# Generated by Django 6.0.5 on 2026-06-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='status_alocacao',
        ),
    ]
