# Generated by Django 6.0.5 on 2026-06-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_escala_status_alocacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoDepartamento',
        ),
    ]
