# Generated by Django 6.0.5 on 2026-06-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_eventodepartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
        ),
    ]
