# Generated by Django 6.0.5 on 2026-06-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_escala_data_alter_evento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='limite_mensal',
        ),
    ]
