# Generated by Django 6.0.5 on 2026-06-01 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pessoa_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departamento'),
        ),
    ]
