# Generated by Django 6.0.5 on 2026-06-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pessoa_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='departamento',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='core.departamento'),
        ),
    ]
