# Generated by Django 6.0.5 on 2026-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pessoa_departamento_pessoa_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='notificacao_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
