# Generated by Django 6.0.5 on 2026-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_escala_notificacao_enviada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='notificacao_enviada',
        ),
        migrations.AddField(
            model_name='escala',
            name='notificacao_24h_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escala',
            name='notificacao_2h_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
